app/donors/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired, Email, NumberRange


class InsertForm(FlaskForm):
	# every insert action has to include donor's name
	name = StringField('Name', validators=[DataRequired()])
	contact_email = StringField('Contact Email', validators=[DataRequired(), Email()])
	donation_amount = IntegerField('Donation Amount ($)', validators=[DataRequired(), NumberRange(min=0)])
	donate_event = StringField('Donate Event')
	submit = SubmitField('Insert')

app/donors/routes.py
from flask import (render_template, Blueprint, url_for, flash, redirect, request, abort)
from flask_login import current_user, login_required
from app import db
from app.models import Donor
from app.donors.forms import InsertForm

donors = Blueprint('donors', __name__)

# Since we posting data back into this route, the route
# needs to have get and post method
@donors.route("/account/add",  methods=['GET', 'POST'])
@login_required
def insert_donor():
    form = InsertForm()
    # If form is valid, post it and return the updated table
    # on account page
    if form.validate_on_submit():
        # add donor to database
        donor = Donor(name=form.name.data, contact_email=form.contact_email.data,
                      donation_amount=form.donation_amount.data, donate_event=form.donate_event.data, admin=current_user)
        db.session.add(donor)
        db.session.commit()
        flash(' A new person data was added', 'success')
        return redirect(url_for('users.account'))
    return render_template('insert_donor.html', form=form, title=' Add Donor', legend='Add Donor')


# function to display a donor's information

@donors.route("/account/<int:donor_id>")
def return_donor(donor_id):
    # get_or_404 is a function returning donor's id if exists, else 404 error
    # Consider show all donations the donor made
    # page = request.args.get('page', 1, type=int)
    # donor = Donor.query.filter_by(id=donor_id).first_or_404()
    # [donation_history]= Donation_history.query.filter_by(donor=donor).order_by(Donor.amount.desc()).paginate(page=page, per_page=5)
    donor = Donor.query.get_or_404(donor_id)
    return render_template('donor.html', title=donor.name, donor=donor)


# function to edit the donor's information
# Design idea: Admin needs to choose a specific donor to edit info

@donors.route("/account/<int:donor_id>/update",  methods=['GET', 'POST'])
@login_required
def update_donor(donor_id):
    donor = Donor.query.get_or_404(donor_id)
    # if admin is not current user, give error
    if donor.admin != current_user:
        abort(403)
    form = InsertForm()
    # If form is valid, change only contact email or donation amount
    # if method is get, we want to the form to be filled ahead
    if form.validate_on_submit():
        donor.contact_email = form.contact_email.data
        donor.donation_amount = form.donation_amount.data
        donor.donate_event = form.donate_event.data
        db.session.commit()
        flash('Information has been updated!', 'success')
        return redirect(url_for('donors.return_donor', donor_id=donor.id))
    elif request.method == 'GET':
        # Get data for name and contact email only
        form.name.data = donor.name
        form.contact_email.data = donor.contact_email
    return render_template('insert_donor.html', title='Update Donor',
                           form=form, legend='Update Donor')


@donors.route("/account/<int:donor_id>/delete", methods=['GET', 'POST'])
@login_required
def delete(donor_id):
    donor = Donor.query.get_or_404(donor_id)
    # verify that user is current user
    if donor.admin != current_user:
        flash('Wrong admin', 'success')
        abort(403)
    db.session.delete(donor)
    db.session.commit()
    flash('One donor information was deleted!', 'success')
    return redirect(url_for('users.account'))

app/main/routes.py
from flask import render_template, request, Blueprint

main = Blueprint('main', __name__)

# Link to home page

@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')

# About page

@main.route("/about")
def about():
    return render_template('about.html', title='About')

app/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User, Donor
from app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm)
from app.users.util import send_reset_email

users = Blueprint('users', __name__)

# Register page

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    # Check if form is valid
    if form.validate_on_submit():
        # Hash password
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # Actually create an instance of user and add them to database
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # import login_user function
            login_user(user, remember=form.remember.data)
            # check if next page exists, get reurns none if next does not exist
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


# Route user account home page, allowing user to update account right at home page

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
   # image_file = url_for('static', filename='profile-pics/' + current_user.image_file)
   form = UpdateAccountForm()
   if form.validate_on_submit():
       current_user.username = form.username.data
       current_user.email = form.email.data
       db.session.commit()
       flash('Your account has been updated!', 'success')
       return redirect(url_for('users.account'))
   elif request.method == 'GET':
       form.username.data = current_user.username
       form.email.data = current_user.email
   return render_template('account1.html', title='Account', form=form)


@users.route("/account/viewall", methods=['GET', 'POST'])
@login_required
def viewall():
    user_id = current_user.id
    page = request.args.get('page', 1, type=int)
    # Query donors of current user (filter_by) and order alphabetically
    # Number them into pages
    donors = Donor.query.filter_by(admin_id=user_id).order_by(Donor.name).paginate(page=page, per_page=3)
    # donors = Donor.query.filter(db.users.id == user_id)
    return render_template('viewall.html', title='Account', donors=donors)

@users.route("/account/update", methods=['GET', 'POST'])
@login_required
def update_account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account1.html', title='Account', form=form)

# Link to request reset password

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    # check if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    # create form
    form = RequestResetForm()
    # if form is submitted, get the user with that email
    # Send them an email to reset password
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to you to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Request', form=form)

# Route to reset password

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    # check if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    user = User.verify_reset_token(token)
    # if function does not return an user, flash an error message
    # redirect to reset request again
    if user is None:
        flash('Invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    # Else if user is valid, present form to reset password
    form = ResetPasswordForm()
    # Handle if form is submitted
    if form.validate_on_submit():
        # Hash password
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        # Actually create an instance of user and add them to database
        db.session.commit()
        flash('Your password has been updated. You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', title='Reset password', form=form)

app/templates/about.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" >
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif+SC:400,600" rel="stylesheet">
    <style type="text/css">
		/* center everything */
		#center-content{
		  margin-left: auto;
		  margin-right: auto;
		  width: 50%;
		  height: 50%;
		  text-align: center;
          font-size: 14px;
		}
		#button
		{
			/* color: white; */
			/*border: 1px solid gray; */
		}
		#content
		{
			text-align: center;
			/* this padding is 25 % of the div content */
			padding-top: 25%;
			/*color: white; */
		}
		body
		{
			font-family: 'Noto Serif SC', serif;
			font: bold;
			background: url(https://images.unsplash.com/photo-1496867557017-559adb93b339?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1051&q=80);
			color: rgb(40,40,40);
			/* resize the image */
			background-size: cover;
			/* change position */
			/* background-position: center; */
			background-repeat: no-repeat;
		}
		h3{
			font-weight: 700;
			/* size of word is 5 times of its parent element */
			font-size: 30px;
		}
		.column {
		position: absolute;
		left: 200px;
}
	</style>

    {% if title %}
    <title>CRUD Flask App - {{ title }}</title>
    {% else %}
    <title>CRUD Flask App</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">CareDB</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                    <a class="nav-item nav-link" href="#">Contact</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout </a>
                    {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

</header>
<main role="main" class="container">
    <div id="center-content" class="center">
        <h3>
            About CareDB
        </h3>
        <hr>
        <p>

CareDB is an online database that allows non-profit organizations to manage their donors' information and communicate with them more effectively.
        </p>
        <h3> About the Creator</h3>
        <p>
            <hr>
Giang is an undergraduate student studying in the US. She aspires to use her skills and knowledge to make people’s lives better. During her time working as a grant writer for her community’s Daycare Center, she was inspired by her boss, who always cared about the children in the center and prioritized their well-being.
        </p>
    <p>
Recognizing that the center needed a more efficient way to manage its donors’ information, Giang created CareDB to make it easier for the center to raise fund in future. She chose CareDB name because Giang believes that you can really change the world if you care enough.

        </p>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="center">
                <h3 style="">
                </h3>
            </div>


            {% block content %}

            {% endblock %}
        </div>
    </div>
</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/templates/account1.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
   <div class="media">
      <img class="rounded-circle account-img" src="{{ url_for('static', filename='profile-pics/kmLYx3lW.jpg') }}">
      <div class="media-body">
         <h3 class="account-heading">
           {{ current_user.username }}
             <!--{{ form.username.data }} -->
         </h3>
         <p class="text-secondary">{{ current_user.email }}</p>
      </div>

   </div>
   <button class="btn btn-info">
      <a id="button" href="{{ url_for('donors.insert_donor') }}">
         Add Donor
      </a>
   </button>
    <button class="btn btn-info" >
      <a id="button" href="{{ url_for('users.viewall') }}">
         View All
      </a>
   </button>
</div>
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
</div>

{% endblock content %}

app/templates/donor.html
{% extends "layout.html" %}

<!-- we want the for loop to overwrite the body's content
of layout, so we wrap it in a content block -->

{% block content %}
<div class="content-section">
   <div class="media">
      <img class="rounded-circle account-img" src="{{ url_for('static', filename='profile-pics/kmLYx3lW.jpg') }}">
      <div class="media-body">
         <h5 class="account-heading">
            {{ donor.name }}
         </h5>
         <p > Contact Email: {{ donor.contact_email }}</p>
      </div>

   </div>
   <button class="btn btn-info btn-sm">
      <a id="button" href="{{ url_for('donors.update_donor', donor_id=donor.id) }}">
         Edit
      </a>
   </button>
    <button class="btn btn-info btn-sm" style="font-face: 'Comic Sans MS'; font-size: larger; color: white; background-color: #e6e6e6" >
      <a id="button" href="{{ url_for('users.viewall') }}">
         View All
      </a>
   </button>
    <button type="button" class="btn btn-info btn-sm" style="font-face: 'Comic Sans MS'; font-size: larger; color: white; background-color: #e6e6e6" data-toggle="modal" data-target="#deleteModal" >
      <a id="button" href="{{ url_for('donors.delete', donor_id=donor.id) }}">
         Delete
      </a>
   </button>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Donor ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('donors.delete', donor_id=donor.id) }}" method="POST">
            <input class="btn btn-danger btn-sm" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

app/templates/home.html
<!DOCTYPE html>
<html>
<head>
	<title>CAREDB - The free and open source database application for everyone </title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css?fbclid=IwAR0Hi3cxcdMHAUavUaWhndNiLQZWgHQIjB758juIlRj_8oQUHXd8DRhHz-o">
	<link href="https://fonts.googleapis.com/css?family=Noto+Serif+SC:400,600" rel="stylesheet">
	<style type="text/css">
		/* center everything */
		#button
		{
			/* color: white; */
			/*border: 1px solid gray; */
		}
		#content
		{
			text-align: center;
			/* this padding is 25 % of the div content */
			padding-top: 25%;
			/*color: white; */
		}
		body
		{
			font-family: 'Noto Serif SC', serif;
			font: bold;
			background: url(https://images.unsplash.com/photo-1496661415325-ef852f9e8e7c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1099&q=80);
			color: white;
			/* resize the image */
			background-size: cover;
			/* change position */
			background-position: right;
			background-repeat: no-repeat;
		}
		h1{
			font-weight: 700;
			/* size of word is 5 times of its parent element */
			font-size: 5em;
		}
	</style>



</head>

<!--
	steps: 
	* create a container
	create the div with class row to create the grid
	the first row has just one column , so set it to col-lg-12
	* put in content by h1, h3, hr, button
	* center everything
	-->
<body>
<nav class="navbar navbar-inverse  navbar-fixed-top">
	<!-- changing container-fluid to conainer to make the content more center -->
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CareDB</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('main.home') }}">Home</a></li>
        <li><a href="{{ url_for('main.about') }}">About</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li> <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a> </li>
          <li> <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout </a> </li>
          {% else %}
          <li><a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a> </li>
          <li><a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a> </li>
          {% endif %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
	<div class="row">
		<div class="col-lg-12">
				<div id="content">
					<!-- h1 would go all the way accross so we need to center it -->
				<h1>CareDB</h1>
				<h3>The Free and Open Source Database for Organizations</h3>
				<hr>
				<!-- the btn is just a boostrap default version we can search on getbootstrap -->
				<button class="btn btn-default btn-lg" >
					<!-- <span id="button" > -->
                        <a id="button" href="{{ url_for('users.register') }}">
                            Register
                        </a>
                   <!--  </span> -->
				</button>
				</div>	
		</div>
	</div>
</div>
<!-- we need jQurry for the navbar and for the javascript file below to work so put this before loading javascript-->
<!-- search jQuerry cdn-->
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>


</body>
</html>

app/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Reset Password </legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/viewall.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
   <div class="media">
      <img class="rounded-circle account-img" src="{{ url_for('static', filename='profile-pics/kmLYx3lW.jpg') }}">
      <div class="media-body">
         <h3 class="account-heading">
            {{ current_user.username }}
         </h3>
         <p class="text-secondary">{{ current_user.email }}</p>
      </div>

   </div>
   <button class="btn btn-info" style="font-face: 'Comic Sans MS'; font-size: larger; color: white; background-color: #e6e6e6" >
      <a id="button" href="{{ url_for('donors.insert_donor') }}">
         Add Donor
      </a>
   </button>
    <button class="btn btn-info" style="font-face: 'Comic Sans MS'; font-size: larger; color: white; background-color: #e6e6e6" >
      <a id="button" href="{{ url_for('users.update_account') }}">
         Update Account
      </a>
   </button>
</div>
<div class="content-section">
   <table class = 'table table-hover' style = 'margin-left: 30px; margin-right: 100px; width: 90%;'>
      <thead>
      <tr>
         <th>Full Name</th>
         <th>Contact Email</th>
         <th>Donation Amount</th>
         <th>Donate Event</th>
         <th>Edit</th>
         <th>Delete</th>
      </thead>

      {% for donor in donors.items %}
      <tr>
         <td> <a id="linkName" href="{{ url_for('donors.return_donor', donor_id=donor.id) }}">{{donor["name"]}} </a></td>
         <td>{{donor["contact_email"]}}</td>
         <td>{{donor['donation_amount']}}</td>
         <td>{{donor['donate_event']}}</td>
          <!-- Allowing user to update -->
         <td align="center"><a id="linkName" href = "{{ url_for('donors.update_donor', donor_id=donor['id']) }}"><i class="fa fa-edit" style="font-size:18px"></i></a></td>
         <!-- Modal is a bootstrap allowing user to confirm they want to delete
          -- <td align="center"><button type="button" class="btn btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button></td>
          -->
          <td align="center"><a id="linkName" href = "{{ url_for('donors.delete', donor_id=donor['id']) }}"><i class="fa fa-trash-alt" style="font-size:18px"></i></a></td>
      </tr>
      {% endfor %}
   </table>
    {% for page_num in donors.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if donors.page == page_num %}
          <a style="color: blue; font-size: 14px" class="btn btn-info mb-4" href="{{ url_for('users.viewall', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a style ="color: blue; font-size: 14px" class="btn btn-outline-info mb-4" href="{{ url_for('users.viewall', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
</div>

{% endblock content %}